#
# board/renesas/salvator-x/Makefile
#
# Copyright (C) 2015 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-y   += sm2s-rzg2l.o
obj-y   += ../../renesas/rcar-common/common.o
obj-y   += boardinfo.o
obj-y   += bootsel.o
